version: '3.8'

services:
  funasr-api:
    image: quantatrisk/funasr-api:latest
    container_name: funasr-api
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "17000:8000"
    volumes:
      - ./models/modelscope:/root/.cache/modelscope
      - ./models/huggingface:/root/.cache/huggingface
      - ./logs:/app/logs
      - ./temp:/app/temp
    environment:
      - ENABLED_MODELS=qwen3-asr-1.7b
      # - HTTPS_PROXY=http://127.0.0.1:20172
    networks:
      - app-network

  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-server
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "17001:8080"
    volumes:
      - ./llama_model:/models
    command: >
      -m /models/Qwen3.5-4B-Q4_K_M.gguf
      -ctk q4_0
      --host 0.0.0.0
      --ctx-size 32768
      --gpu-layers 99
      --flash-attn on
      --chat-template-kwargs '{"enable_thinking": false}'
      --repeat-penalty 1.0
      --presence-penalty 1.5
      --min-p 0.0
      --top-k 20
      --top-p 0.8
      --temp 0.7
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
